# Generated by Django 3.1.2 on 2020-11-08 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='date_of_crime',
        ),
        migrations.RemoveField(
            model_name='public',
            name='time_of_crime',
        ),
        migrations.AddField(
            model_name='public',
            name='crime_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='crime_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
