# Generated by Django 3.1.2 on 2020-11-12 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201108_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='city_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
